### ISSUE TITLE
about not enough funds

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lightning-node#12]
Hi there, I have set up a testnet node on my local machine here, and I run createutxo, issueassets, and sendbtc interface, the errors comes out:
Not enough funds, call getaddress and send 1000178 satoshis.
So, the question is, how do you generate satoshis and send them to a specific address? (which interface to call?)

**Comment by zoedberg** [comment]
If you google "bitcoin testnet faucet" you'll find several services offering free testnet bitcoins. Call the `/address` API to obtain an address, give it to the faucet and then wait for it to send you some sats. After receiving enough sats you'll be able to create utxos, which is needed to issue assets.

**Comment by cymqqqq** [comment]
thanks for answering, another question is: If I have set up a lightning node, do I must to obtain test bitcoins by faucet, or are there already some initialized tested bitcoins on my unlocked lightning node?

**Comment by zoedberg** [comment]
This is not possible because it would mean hardcoding a fixed seed, that users could then also "empty-out". If you are having hard times getting testnet bitcoins I suggest trying the node on regtest, where you can send arbitrary amounts of bitcoins to the node and mine at will, it should simplify testing a lot.

**Comment by cymqqqq** [comment]
Hi @zoedberg , I'm here again, so I have set up the regtest node at daemon 3001 port as you told me, and then next step which interface should I call? (I have read all interfaces, but none of them are related to "send satoshi", maybe I made some wrong steps?)

**Comment by zoedberg** [comment]
> Did I miss something? Or all four steps can build a complete procedure?

I'm not sure what do you mean for "complete procedure". What you could try now is to run a second node and try to open a channel with it. Anyway, the reported issue seems to be fixed so I'll close this. Feel free to open a new issue in case you encounter other problems
