### ISSUE TITLE
custom interface

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lightning-node#14]
Hi Team, I have a question about how to add a customized interface, such as the list_transactions interface. I want to add a new interface, list_transaction_by_id, which can be queried by a transaction id. I searched in rgb-lib repo, there is a _list_transaction function in the source code, but it's internal.

**Comment by zoedberg** [comment]
Hi! We don't see this task as urgent since right now you can already filter the transaction list to search by TXID on the client-side. Closing this for now, we'll evaluate performance optimizations tasks in the future
