### ISSUE TITLE
build: update axum to 0.7.x

### ISSUE THREAD

**Issue by bitlightlabs-dev** [RGB-Tools/rgb-lightning-node#15]
axum 0.6.19 -> 0.7.2
axum-extra 0.7.5 -> 0.9.0
hyper 0.14.27 -> 1.0.1

**Comment by zoedberg** [comment]
Thanks, this is on our roadmap, will do that after a big PR that we are waiting to be opened.

**Comment by zoedberg** [comment]
Done in https://github.com/RGB-Tools/rgb-lightning-node/commit/3c74d87765f0b589f23f6f783905e4f630d43563
