### ISSUE TITLE
question about issue amount limit when I issue a new rgb asset

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lightning-node#19]
Hi there,  when I want to issue a new rgb asset, there are four parameters: amount, ticker, name, and precision. I have a question from our test engineer: are there any limits for the issue amount, such as it can not surpass a threshold?
And I found no interface about how to get the maximum issue amount here.

**Comment by nicbus** [comment]
Hi, seems like you're talking about a NIA asset.

NIA schema (RGB20 interface) has a maximum supply of 2^64. Trying to issue an asset that exceeds that limit will return a `TooHighIssuanceAmounts` error.
