### ISSUE TITLE
cargo build question

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lightning-node#22]
Hi there, I found that we used cargo install --debug --path . command here.
Can we use cargo build --release instead of cargo install --debug --path . ?(or other compile command)

**Comment by nicbus** [comment]
We had several issues in the past with release mode (see e.g. [this issue](https://github.com/RGB-Tools/rgb-lib/issues/27)). Moreover, even though `cargo build --release` works, `cargo install --path .` still fails. We'll update the README once the issues will have been addressed.
