### ISSUE TITLE
BTC RPC args parsing expect host:port URL format only

### ISSUE THREAD

**Issue by gofman8** [RGB-Tools/rgb-lightning-node#35]
https://github.com/RGB-OS/rgb-lightning-node/blob/04f786290068fc14c8a1c43279cd6fe5d686d67d/src/args.rs#L57

As far as we can see, the following code expects that BTC RPC endpoint URL is reached though TCP protocol, though host:port format and HTTP/HTTPS is not supported.  All cloud services which provides RPC endpoints provide access to their node though HTTPS, using similar format: ```https://rpc.ankr.com/btc_signet/370cf9bd72bce432bf016asfasfafsafaf8592d5e5ad36abc42c5d881b199e1```

So seems to be the only way to run RLN on testnet so far is to start your own BTCD node locally which is adds additional level of prerequisites, costs and complexity. 

**UPD**: sorry, found the you have user:password@electrum.iriswallet.com:18332 open to public, it's good but still would be good to have possibility to use BTC RPC over HTTPS

**Comment by zoedberg** [comment]
> still would be good to have possibility to use BTC RPC over HTTPS

AFAIU bitcoind doesn't support that: https://en.bitcoin.it/wiki/Enabling_SSL_on_original_client_daemon

Therefore I don't think we can support this on RLN
