### ISSUE TITLE
Channel Opening Fails Without IP Address: Peer Info Address Not Found

### ISSUE THREAD

**Issue by bitwalt** [RGB-Tools/rgb-lightning-node#38]
Hi! 
We’ve encountered an issue with channel opening when an IP address is not provided. Currently, the channel opening using just the pubkey as connection string, is only successful if the initiator of the channel is the same node that executed the /connectpeer command first.

The failure occurs with the error: Invalid peer info: cannot find the address for the provided pubkey.

**Comment by zoedberg** [comment]
Thanks for reporting this, I've pushed a fix and will merge the PR as soon as the CI passes
