### ISSUE TITLE
Question about PaymentPreimage and PaymentHash implementation in keysend function

### ISSUE THREAD

**Issue by UnCooe** [RGB-Tools/rgb-lightning-node#45]
Hi,

I noticed in the keysend function that PaymentPreimage and PaymentHash are being used, as shown in the following code snippet:

let payment_preimage = PaymentPreimage(unlocked_state.keys_manager.get_secure_random_bytes());
let payment_hash_inner = Sha256::hash(&payment_preimage.0[..]).to_byte_array();
let payment_hash = PaymentHash(payment_hash_inner);
I was reviewing the keysend implementation and noticed the usage of PaymentPreimage() and PaymentHash() in the code. However, I couldn't find any explicit implementation for these constructors or methods within the project.

Could you clarify if these are implemented elsewhere, or if they are placeholders to be implemented in the future? I’m concerned this might affect the keysend flow as it seems these constructs are integral to the payment process.

Thank you for your time and all the effort you've put into this project!

Best regards,
uncooe

**Comment by UnCooe** [comment]
@zoedberg 😃

**Comment by zoedberg** [comment]
>  I was reviewing the keysend implementation and noticed the usage of PaymentPreimage() and PaymentHash() in the code. However, I couldn't find any explicit implementation for these constructors or methods within the project.
>
> Could you clarify if these are implemented elsewhere, or if they are placeholders to be implemented in the future?

They are imported here
https://github.com/RGB-Tools/rgb-lightning-node/blob/e8f24cf086d629e39e30fd6f42f31c7b71194af8/src/routes.rs#L24-L27
which means they are implemented in the lightning crate (that we import from the local submodule). In https://github.com/RGB-Tools/rust-lightning/blob/adbe96ad878918dfa024b243db5fe2f8ba153bb4/lightning/src/ln/types.rs you can find their implementation.

**Comment by UnCooe** [comment]
Sorry, it’s my fault. I must have accidentally deleted it while adding comments.
