### ISSUE TITLE
Compatibility issue with ./regtest.sh start on macOS

### ISSUE THREAD

**Issue by UnCooe** [RGB-Tools/rgb-lightning-node#46]
Hello,

I've encountered an issue while running the ./regtest.sh start command from the rgb-lightning-node library:

On a Linux system, the command works successfully without any issues.
However, on macOS, it fails with the following error:
preparing bitcoind wallet
error: timeout on transient error: Could not connect to the server 127.0.0.1:18443

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
error: timeout on transient error: Could not connect to the server 127.0.0.1:18443

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
It seems that the script is unable to connect to bitcoind on macOS. Could you please look into adding compatibility for macOS systems? This would greatly enhance the usability of the library across platforms.

Thank you for your work on this amazing project!

**Comment by zoedberg** [comment]
At the moment adding compatibility for ARM-based macOS systems is not in our roadmap. The `regtest.sh` script is meant for testing on x86_64-based Unix systems.

But RLN should run on every system, so if you want to use it on regtest you can just manually run the necessary services locally or in docker.
